// import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import { useAuth } from "../Context/Auth-context";
import { useEffect, useState } from "react";
import Link from "next/link";
import "../Config/i18nextConf";
import Sliderreviews from "../components/Sliderreviews";
import { getReviewsData } from "../Connection/Order";

export default function Home({ child }) {
  const { loggedIn, loggedinUser, setLoggedinUser, setLoggedIn } = useAuth();
  const [width, setWidth] = useState();
  const [reviews, setReviews] = useState([]);

  useEffect(() => {
    const getReviews = async () => {
      let res = await getReviewsData();
      console.log(res);
      if (res.data.success === true) {
        console.log(res.data.data);
        setReviews(res.data.reviews);
      }
    };

    getReviews();
    setWidth(window.innerWidth);
    console.log(loggedinUser);
    console.log("Index is running");
  }, []);

  return (
    <div className="container">
      <Head>
        <title>Easy Dine</title>
        <meta name="description" content="Generated by MAT" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col-12">
          <div className={styles.section1}>
            <br />
            <br />
            <br />
            <h1
              style={{ fontWeight: "400" }}
              className=" display-4 text-center text-light mt-5"
            >
              Welcome to <span className="text-danger">Easy Dine</span>
            </h1>
            <hr style={{ borderTop: "2px solid #FFFFFF", width: "40%" }} />
            <p
              style={{ fontSize: "25px" }}
              className="text-center text-light display-5"
            >
              Where You Can Focus On Your Food
            </p>
            <div className="text-center">
              {" "}
              <button className="btn btn-danger">
                {" "}
                <Link style={{ textDecoration: "none" }} href="/menu">
                  Check Menu
                </Link>
              </button>
            </div>
          </div>
        </div>

        {/* <div className="col-12 col-md-6 mt-4  px-3 d-flex justify-content-center">
          <h1 style={{ fontSize: "75px" }} className="mx-4 mt-4">
            Welcome to Easy Dine <span className="text-danger">.</span>
          </h1>
          {width <= 768 ? (
            <h1 style={{ fontSize: "75px" }} className="mx-4 mt-4">
              Welcome to Easy Dine{" "}
              <span className="text-danger">
                . Where You Can Focus On Your Food
              </span>
            </h1>
          ) : (
            ""
          )}
        </div> */}
        {/* <div className="col-12 col-md-6 d-flex justify-content-center">
          <img
            className="img-fluid"
            style={{ borderRadius: "12px" }}
            src="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60"
          />
          <br />
        </div> */}
      </div>
      <br />
      <br />
      {/* <div className="row">
        <div className="col-12 col-md-6 d-flex justify-content-center">
          <img
            className="img-fluid "
            style={{ borderRadius: "12px" }}
            src="https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60"
          />
        </div>
        <div className="col-12 col-md-6  px-3 d-flex justify-content-center">
          <h1 style={{ fontSize: "75px" }} className="mx-4 mt-4">
            Where You Can Focus On Your Food{" "}
            <span className="text-danger">.</span>
          </h1>
          {width <= 768 ? (
            <h1 style={{ fontSize: "75px" }} className="mx-4 mt-4">
              Welcome to Easy Dine{" "}
              <span className="text-danger">
                . Where You Can Focus On Your Food
              </span>
            </h1>
          ) : (
            ""
          )}

          {width > 768 && width < 1440 ? (
            <h1 style={{ fontSize: "90px" }} className="mx-4 mt-4">
              Welcome to Easy Dine{" "}
              <span className="text-danger">
                . Where You Can Focus On Your Food
              </span>
            </h1>
          ) : (
            ""
          )}

          {width >= 1440 ? (
            <h1 style={{ fontSize: "115px" }} className="mx-4 mt-4">
              Welcome to Easy Dine{" "}
              <span className="text-danger">
                . Where You Can Focus On Your Food
              </span>
            </h1>
          ) : (
            ""
          )}
        </div>
      </div> */}
      <br />
      <br />
      <div className="container">
        {" "}
        <div className="row ">
          <div className="col-12 text-center">
            <div
              style={{
                width: "100%",
                height: "200px",
                border: "1px solid #E6034D",
                borderRadius: "12px",
              }}
            >
              <h2 className="mt-5">Lets Explore Our Menu Here</h2>
              <button className="btn btn-outline-danger">
                <Link style={{ textDecoration: "none" }} href="/menu">
                  Explore Our Menu
                </Link>
              </button>
            </div>
          </div>
        </div>
      </div>

      <br />
      <br />
      <div className="text-center">
        <h2>
          Reviews <span className="text-danger">.</span>
        </h2>
        <br />
        <div className="row">
          <div className="col-12 col-md-6 mt-4 mb-2">
            <h4>
              What Our Happy Clients Says about us{" "}
              <span className="text-danger">.</span>
            </h4>
          </div>
          {reviews && (
            <div className="col-12 col-md-6">
              <Sliderreviews reviews={reviews} />
            </div>
          )}
        </div>
      </div>

      <br />
      <br />
    </div>
  );
}
